CREATE table continent(
    id_continent int AUTO_INCREMENT PRIMARY KEY,
    name varchar(255) NOT NULL UNIQUE
    );
CREATE table country(
    id_country int AUTO_INCREMENT PRIMARY KEY,
    name varchar(255) not null UNIQUE,
    pop bigint,
    lang varchar(255) not null,
    id_continent int,
    FOREIGN KEY(id_continent) REFERENCES continent(id_continent)
    ON DELETE CASCADE
    );
CREATE table city(
    id_city int AUTO_INCREMENT PRIMARY KEY,
    name varchar(255) not null UNIQUE,
    type ENUM('Capital','other'),
    id_country int,
    FOREIGN KEY(id_country) REFERENCES country(id_country)
    ON DELETE CASCADE
    );

CREATE TABLE users(
    user varchar(255) UNIQUE,
    pass varchar(255) UNIQUE,
    email varchar(255) UNIQUE,
    isadmin tinyint DEFAULT 0,
    user_id int NOT NULL AUTO_INCREMENT PRIMARY KEY
    );

INSERT INTO country(name,pop,lang,id_continent)
VALUES
("Algeria", 43900000, "Arabic, Berber", 5),
("Angola", 31825295, "Portuguese", 5),
("Benin", 10653654, "French", 5),
("Botswana", 2141206, "English, Setswana", 5),
("Burkina Faso", 19034397, "French", 5),
("Burundi", 10114505, "Kirundi, French, English", 5),
("Cabo Verde", 531239, "Portuguese", 5),
("Cameroon", 22709892, "French, English", 5),
("Central African Republic", 4998000, "Sango, French", 5),
("Chad", 14497000, "Arabic, French", 5),
("Comoros", 806153, "Comorian, Arabic, French", 5),
("Congo (Congo-Brazzaville)", 4741000, "French", 5),
("Democratic Republic of the Congo (Congo-Kinshasa)", 90000000, "French", 5),
("Djibouti", 900000, "Arabic, French", 5),
("Egypt", 104124000, "Arabic", 5),
("Equatorial Guinea", 1402985, "Spanish, French, Portuguese", 5),
("Eritrea", 3546064, "Tigrinya, Arabic, English", 5),
("Eswatini", 1160164, "English, siSwati", 5),
("Ethiopia", 120000000, "Amharic", 5),
("Gabon", 2112275, "French", 5),
("Gambia", 2410000, "English", 5),
("Ghana", 31072940, "English", 5),
("Guinea", 13100000, "French", 5),
("Guinea-Bissau", 2000000, "Portuguese", 5),
("Ivory Coast", 25823071, "French", 5),
("Kenya", 53771000, "Swahili, English", 5),
("Lesotho", 2020000, "Sesotho, English", 5),
("Liberia", 5060000, "English", 5),
("Libya", 6871287, "Arabic", 5),
("Madagascar", 27691018, "Malagasy, French", 5),
("Malawi", 19800000, "English, Chichewa", 5),
("Mali", 20250000, "Bambara, French", 5),
("Mauritania", 4500000, "Arabic", 5),
("Mauritius", 1250000, "English, French", 5),
("Morocco", 37000000, "Arabic, Berber", 5),
("Mozambique", 31255435, "Portuguese", 5),
("Namibia", 2320000, "English", 5),
("Niger", 24000000, "French", 5),
("Nigeria", 206140000, "English", 5),
("Rwanda", 12000000, "Kinyarwanda, French, English", 5),
("São Tomé and Príncipe", 200000, "Portuguese", 5),
("Senegal", 16900000, "French", 5),
("Seychelles", 98000, "English, French, Seychellois Creole", 5),
("Sierra Leone", 8000000, "English", 5),
("Somalia", 16000000, "Somali, Arabic", 5),
("South Africa", 59308690, "Afrikaans, English, Zulu, Xhosa", 5),
("South Sudan", 8000000, "English", 5),
("Sudan", 43000000, "Arabic, English", 5),
("Togo", 8190000, "French", 5),
("Tunisia", 11818619, "Arabic", 5),
("Uganda", 45200000, "English, Swahili", 5),
("Zambia", 18000000, "English", 5),
("Zimbabwe", 14100000, "English, Shona, Ndebele", 5);

INSERT INTO city(name,type,id_country)
VALUES
("Algiers", "Capital", 3),
("Oran", "Other", 3),
("Constantine", "Other", 3),
("Annaba", "Other", 3),
("Blida", "Other", 3),

("Luanda", "Capital", 4),
("Huambo", "Other", 4),
("Benguela", "Other", 4),
("Lubango", "Other", 4),
("Malanje", "Other", 4),

("Porto-Novo", "Capital", 5),
("Cotonou", "Other", 5),
("Parakou", "Other", 5),
("Abomey", "Other", 5),
("Bohicon", "Other", 5),

("Gaborone", "Capital", 6),
("Francistown", "Other", 6),
("Molepolole", "Other", 6),
("Maun", "Other", 6),
("Selibe Phikwe", "Other", 6),

("Ouagadougou", "Capital", 7),
("Bobo-Dioulasso", "Other", 7),
("Koudougou", "Other", 7),
("Banfora", "Other", 7),
("Ouahigouya", "Other", 7),

("Bujumbura", "Capital", 8),
("Gitega", "Other", 8),
("Ngozi", "Other", 8),
("Rutana", "Other", 8),
("Bururi", "Other", 8),

("Praia", "Capital", 9),
("Mindelo", "Other", 9),
("Santa Maria", "Other", 9),
("Espargos", "Other", 9),
("Tarrafal", "Other", 9),

("Yaoundé", "Capital", 10),
("Douala", "Other", 10),
("Bamenda", "Other", 10),
("Bafoussam", "Other", 10),
("Garoua", "Other", 10),

("Bangui", "Capital", 11),
("Berbérati", "Other", 11),
("Bouar", "Other", 11),
("Bossangoa", "Other", 11),
("Bambari", "Other", 11),

("N'Djamena", "Capital", 12),
("Moundou", "Other", 12),
("Sarh", "Other", 12),
("Abeche", "Other", 12),
("Koumra", "Other", 12),


("Moroni", "Capital", 13),
("Mutsamudu", "Other", 13),
("Fomboni", "Other", 13),
("Domoni", "Other", 13),
("Ouani", "Other", 13),

("Brazzaville", "Capital", 14),
("Pointe-Noire", "Other", 14),
("Dolisie", "Other", 14),
("Nkayi", "Other", 14),
("Owando", "Other", 14),

("Kinshasa", "Capital", 15),
("Lubumbashi", "Other", 15),
("Mbuji-Mayi", "Other", 15),
("Kisangani", "Other", 15),
("Kananga", "Other", 15),

("Djibouti", "Capital", 16),
("Ali Sabieh", "Other", 16),
("Dikhil", "Other", 16),
("Obock", "Other", 16),
("Tadjoura", "Other", 16),

("Cairo", "Capital", 17),
("Alexandria", "Other", 17),
("Giza", "Other", 17),
("Luxor", "Other", 17),
("Aswan", "Other", 17),

("Malabo", "Capital", 18),
("Bata", "Other", 18),
("Ebebiyin", "Other", 18),
("Aconibe", "Other", 18),
("Mongomo", "Other", 18),

("Asmara", "Capital", 19),
("Keren", "Other", 19),
("Massawa", "Other", 19),
("Mendefera", "Other", 19),
("Assab", "Other", 19),

("Mbabane", "Capital", 20),
("Manzini", "Other", 20),
("Lobamba", "Other", 20),
("Siteki", "Other", 20),
("Nhlangano", "Other", 20),

("Addis Ababa", "Capital", 21),
("Dire Dawa", "Other", 21),
("Mekelle", "Other", 21),
("Bahir Dar", "Other", 21),
("Adama", "Other", 21),

("Libreville", "Capital", 22),
("Port-Gentil", "Other", 22),
("Franceville", "Other", 22),
("Oyem", "Other", 22),
("Moanda", "Other", 22),

("Banjul", "Capital", 23),
("Serrekunda", "Other", 23),
("Brikama", "Other", 23),
("Bakau", "Other", 23),
("Farafenni", "Other", 23),

("Accra", "Capital", 24),
("Kumasi", "Other", 24),
("Tamale", "Other", 24),
("Takoradi", "Other", 24),
("Cape Coast", "Other", 24),

("Conakry", "Capital", 25),
("Nzérékoré", "Other", 25),
("Kankan", "Other", 25),
("Labé", "Other", 25),
("Kindia", "Other", 25),

("Bissau", "Capital", 26),
("Bafatá", "Other", 26),
("Gabu", "Other", 26),
("Cacheu", "Other", 26),
("Bolama", "Other", 26),

("Yamoussoukro", "Capital", 27),
("Abidjan", "Other", 27),
("Bouaké", "Other", 27),
("Daloa", "Other", 27),
("San Pedro", "Other", 27),

("Nairobi", "Capital", 28),
("Mombasa", "Other", 28),
("Kisumu", "Other", 28),
("Nakuru", "Other", 28),
("Eldoret", "Other", 28),

("Maseru", "Capital", 29),
("Teyateyaneng", "Other", 29),
("Mafeteng", "Other", 29),
("Hlotse", "Other", 29),
("Quthing", "Other", 29),

("Monrovia", "Capital", 30),
("Gbarnga", "Other", 30),
("Buchanan", "Other", 30),
("Harper", "Other", 30),
("Zwedru", "Other", 30),

("Tripoli", "Capital", 31),
("Benghazi", "Other", 31),
("Misrata", "Other", 31),
("Bayda", "Other", 31),
("Zawiya", "Other", 31),


("Antananarivo", "Capital", 32),
("Toamasina", "Other", 32),
("Fianarantsoa", "Other", 32),
("Mahajanga", "Other", 32),
("Toliara", "Other", 32),

("Lilongwe", "Capital", 33),
("Blantyre", "Other", 33),
("Mzuzu", "Other", 33),
("Zomba", "Other", 33),
("Mangochi", "Other", 33),

("Bamako", "Capital", 34),
("Sikasso", "Other", 34),
("Mopti", "Other", 34),
("Gao", "Other", 34),
("Kayes", "Other", 34),

("Nouakchott", "Capital", 35),
("Nouadhibou", "Other", 35),
("Kaédi", "Other", 35),
("Rosso", "Other", 35),
("Zouerate", "Other", 35),

("Port Louis", "Capital", 36),
("Beau Bassin-Rose Hill", "Other", 36),
("Vacoas-Phoenix", "Other", 36),
("Curepipe", "Other", 36),
("Quatre Bornes", "Other", 36),

("Rabat", "Capital", 37),
("Casablanca", "Other", 37),
("Marrakech", "Other", 37),
("Fes", "Other", 37),
("Tangier", "Other", 37),

("Maputo", "Capital", 38),
("Beira", "Other", 38),
("Nampula", "Other", 38),
("Matola", "Other", 38),
("Quelimane", "Other", 38),

("Windhoek", "Capital", 39),
("Walvis Bay", "Other", 39),
("Swakopmund", "Other", 39),
("Rundu", "Other", 39),
("Oshakati", "Other", 39),

("Niamey", "Capital", 40),
("Zinder", "Other", 40),
("Maradi", "Other", 40),
("Agadez", "Other", 40),
("Tahoua", "Other", 40),

("Abuja", "Capital", 41),
("Lagos", "Other", 41),
("Kano", "Other", 41),
("Ibadan", "Other", 41),
("Port Harcourt", "Other", 41),

("Kigali", "Capital", 42),
("Butare", "Other", 42),
("Gisenyi", "Other", 42),
("Muhanga", "Other", 42),
("Ruhengeri", "Other", 42),

("São Tomé", "Capital", 43),
("Trindade", "Other", 43),
("Neves", "Other", 43),
("Santana", "Other", 43),
("Guadalupe", "Other", 43),

("Dakar", "Capital", 44),
("Touba", "Other", 44),
("Thiès", "Other", 44),
("Ziguinchor", "Other", 44),
("Saint-Louis", "Other", 44),

("Victoria", "Capital", 45),
("Anse Boileau", "Other", 45),
("Beau Vallon", "Other", 45),
("Bel Ombre", "Other", 45),
("Cascade", "Other", 45),

("Freetown", "Capital", 46),
("Bo", "Other", 46),
("Kenema", "Other", 46),
("Makeni", "Other", 46),
("Koidu", "Other", 46),

("Mogadishu", "Capital", 47),
("Hargeisa", "Other", 47),
("Bosaso", "Other", 47),
("Kismayo", "Other", 47),
("Baidoa", "Other", 47),

("Pretoria", "Capital", 48),
("Johannesburg", "Other", 48),
("Cape Town", "Other", 48),
("Durban", "Other", 48),
("Bloemfontein", "Other", 48),

("Juba", "Capital", 49),
("Malakal", "Other", 49),
("Wau", "Other", 49),
("Bor", "Other", 49),
("Yambio", "Other", 49),

("Khartoum", "Capital", 50),
("Omdurman", "Other", 50),
("Port Sudan", "Other", 50),
("Nyala", "Other", 50),
("Kassala", "Other", 50),

("Lomé", "Capital", 51),
("Sokodé", "Other", 51),
("Kara", "Other", 51),
("Atakpamé", "Other", 51),
("Dapaong", "Other", 51),

("Tunis", "Capital", 52),
("Sfax", "Other", 52),
("Sousse", "Other", 52),
("Gabès", "Other", 52),
("Bizerte", "Other", 52),

("Kampala", "Capital", 53),
("Gulu", "Other", 53),
("Mbarara", "Other", 53),
("Jinja", "Other", 53),
("Entebbe", "Other", 53),

("Lusaka", "Capital", 54),
("Kitwe", "Other", 54),
("Ndola", "Other", 54),
("Livingstone", "Other", 54),
("Chipata", "Other", 54),

("Harare", "Capital", 55),
("Bulawayo", "Other", 55),
("Chitungwiza", "Other", 55),
("Mutare", "Other", 55),
("Gweru", "Other", 55);